### ISSUE TITLE
Cannot reproduce results in the paper

### ISSUE THREAD

**Issue by lxxue** [yanqingan/SfM_Disambiguation#1]
Hi Qingan,

Thanks for the interesting work and sharing the code. I tried run it with the newest `bundler_sfm` on the Temple of Heaven dataset and it gives me such results:
\
![bundler_TOH](https://user-images.githubusercontent.com/22346567/100763344-54582900-33f5-11eb-8b1b-1d5a19d9c700.png)

It seems that the result is not correct as in the paper the cameras are all around the scene. Therefore, half of the scene is not reconstructed correctly. I wonder if you have tried this bundler version on the TOH dataset and got similar results in the paper? 

I tried with the `bundler_sfm` with its example dataset `kermit` and the reconstruction looks similar to the reference, so I guess the bundler part is correct.

Also a side question, how do you usually view the reconstruction visually and check if the result is better or not? Is it through the reprojection error and number of tracks? I find the rendered images in the paper are really nice and clear.

**Comment by llcc343** [comment]
Same problems here. Even with finetune the parameters the author recommended, the results are still very bad. I think the results in their paper are fake results. Very sad:(

**Comment by lxxue** [comment]
Actually, I just got a nice result:
![image](https://user-images.githubusercontent.com/22346567/101224496-1118e700-368f-11eb-91f9-0168b09a0f00.png)
The difference is that now I use the version of Bundler in the repo, with a modification in line 9 of `src/Makefile`:
```
OTHERFLAGS=-std=gnu++0x -fPIC
```
so that it compiles successfully on ubuntu 18.04. (also need to replace one file in `lib/sba-1.5` as instructed here: https://github.com/snavely/bundler_sfm/issues/74#issue-565635197).

I will check the reason why it didn't work in the first place later.

**Comment by llcc343** [comment]
Well, I did not use sba for optimization, and use ceres solver in bundler sfm. But the ambiguation is not eliminated. Have you ever test on other ambiguous datasets?

**Comment by lxxue** [comment]
Yeah, it works on the Alexander Nevsky Cathedral dataset. But there are also quite some failure cases.
